# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vx < Formula
  desc "Vault-backed secret manager for monorepos"
  homepage "https://github.com/dotindustries/vx"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dotindustries/vx/releases/download/v0.0.3/vx_0.0.3_darwin_amd64.tar.gz"
      sha256 "ff83d3476ca988971df9991049e53f2907392fb1b05bc78e5acdb594e391b280"

      def install
        bin.install "vx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dotindustries/vx/releases/download/v0.0.3/vx_0.0.3_darwin_arm64.tar.gz"
      sha256 "c5ec1ccf52d92bd503bdb18a49d5ced8a823e4d41ebe2c32982e74072ad34e33"

      def install
        bin.install "vx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dotindustries/vx/releases/download/v0.0.3/vx_0.0.3_linux_amd64.tar.gz"
      sha256 "07017e7f6a55468f764ae44bf156c12f0f8e4025c565d08eae86364cdf29995b"
      def install
        bin.install "vx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dotindustries/vx/releases/download/v0.0.3/vx_0.0.3_linux_arm64.tar.gz"
      sha256 "92051ffd09a8e48cae79d8e77c9194d0641dde34e4d8576fc4ba43068f8ed7ab"
      def install
        bin.install "vx"
      end
    end
  end
end
