# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vx < Formula
  desc "Vault-backed secret manager for monorepos"
  homepage "https://github.com/dotindustries/vx"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dotindustries/vx/releases/download/v0.0.2/vx_0.0.2_darwin_amd64.tar.gz"
      sha256 "999867bc3e574a4418823b80935fa78e43cc232d91c52edb349865ef8cac74b5"

      def install
        bin.install "vx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dotindustries/vx/releases/download/v0.0.2/vx_0.0.2_darwin_arm64.tar.gz"
      sha256 "958aeafc38128d994e07204e8f151980b2aba93aa6f49aee028ef8a462511c79"

      def install
        bin.install "vx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dotindustries/vx/releases/download/v0.0.2/vx_0.0.2_linux_amd64.tar.gz"
      sha256 "671a9aa870bce82453715e0df2182b906b4425edba57e5274346e7b8f7357576"
      def install
        bin.install "vx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dotindustries/vx/releases/download/v0.0.2/vx_0.0.2_linux_arm64.tar.gz"
      sha256 "d03a6fcadb80421b2434a4873296ec88fb9f44e67c36905ced5b472b8a99e7a8"
      def install
        bin.install "vx"
      end
    end
  end
end
